# generate from notebook: !conda env export > environment.yml
name: notebook_python_3.5

channel:
    - conda-forge

dependencies:
  - python=3.5
  - ipywidgets=7.2.1
  - matplotlib=3.0.0
  - numpy=1.15.2
  - pandas=0.23.4
  - scipy=1.1.0
  - seaborn=0.9.0
  - time=1.8
  - pip:
    - pyvacon==0.9.0
    - jupyter-contrib-nbextensions==0.5.1