name: notebook_python_3.5

dependencies:
  - python=3.5
  - pyvacon
  - numpy
  - scipy
  - math
  - datetime
  - dateutil
  - matplotlib
  - ipywidgets
  - pandas
  - random
  - seaborn
  - time
  - mpl_toolkits